Make vm_segment_destroy() and vm_segment_destroy_range() more consistent
cahirwpz/mimiker pull request #1006
Opened 2021-02-18 12:08 UTC by j-piecuch

`vm_segment_destroy()` currently doesn't unmap its address range, while `vm_segment_destroy_range()` does.
To fix this, we introduce `vm_segment_destroy_unmapped()`, which does exactly what `vm_segment_destroy()` used to do, and make `vm_segment_destroy()` unmap its address range before calling `vm_segment_destroy_unmapped()`. No one is actually using `vm_segment_destroy()` now, but I decided to include it in case it's needed in the future.

2021-03-08 00:48 UTC, wiklam reviewed
Your change is lgtm, but do we really need the `vm_segment_destroy` function if it is not used right now?

2021-03-08 00:48 UTC, wiklam commented on sys/kern/vm_map.c
>    assert(start >= vm_map_start(map) && end <= vm_map_end(map));
IMO here we should check also that the start and end are inside a segment.

2021-03-08 00:49 UTC, wiklam approved these changes
LGTM

2021-03-12 17:30 UTC, franciscozdo requested changes
I don't thing we need this change now. Our VM system will be changed in near future by sth like [UVM](https://man.netbsd.org/uvm.9). I think that no one will be using this new `vm_segment_destroy()` function before this change.

2021-03-19 11:36 UTC, j-piecuch commented
Closing, as the VM code in question will likely be replaced in the near future.

2021-03-19 11:36 UTC, closed without merging