Add the AMD64 QEMU target.
cahirwpz/mimiker pull request #1059
Opened 2021-03-25 22:52 UTC by MichalBlk

2021-03-27 12:12 UTC, cahirwpz requested changes

2021-03-27 12:12 UTC, cahirwpz commented on toolchain/qemu-mimiker/debian/changelog
> +qemu-mimiker (4.2.1+mimiker1) unstable; urgency=medium
Please bump up version.

2021-03-27 12:12 UTC, cahirwpz commented on toolchain/qemu-mimiker/debian/changelog
> + -- Krystian Bacławski <cahirwpz@cs.uni.wroc.pl>  Fri, 26 Mar 2021 16:01:25 +0100
Please update date with output from `date -R` command.

2021-03-28 13:11 UTC, MichalBlk commented on toolchain/qemu-mimiker/debian/changelog
> +qemu-mimiker (4.2.1+mimiker1) unstable; urgency=medium
Done.

2021-03-28 13:11 UTC, MichalBlk commented on toolchain/qemu-mimiker/debian/changelog
> + -- Krystian Bacławski <cahirwpz@cs.uni.wroc.pl>  Fri, 26 Mar 2021 16:01:25 +0100
Done.

2021-03-29 15:47 UTC, cahirwpz approved these changes

2021-03-29 15:48 UTC, merged