UVM: basic implementation of amap
cahirwpz/mimiker pull request #1072
Opened 2021-04-03 23:18 UTC by pj1031999

It's a first step for new virtual memory subsystem in Mimiker.

amap describes an area of anonymous memory. It 's a upper layer of UVM’s two-layer mapping scheme.

* Add missing PAGE_SHIFT definition in vm_param for AArch64 & mips.
* Add definition of uvm_amap.
* Add interface for uvm_amap.
* Add definition of uvm_aref.
* Add simple test for uvm_amap.

It's based on NetBSD implementation [1] described by Cranor [2].

[1] https://nxr.netbsd.org/xref/src/sys/uvm/uvm_amap.c
[2] https://chuck.cranor.org/p/diss.pdf

2021-04-06 05:59 UTC, franciscozdo requested changes
I would be happy to see assertions about held lock in functions that require it (at least in functions `*_nolock`). It could help in future.

2021-04-06 06:03 UTC, franciscozdo commented
What do you think about moving tests into `sys/tests/uvm.c`. Then we will have all tests in one place.

2021-04-06 10:47 UTC, pj1031999 commented on sys/kern/uvm_amap.c
> +  uvm_amap_t *amap = pool_alloc(P_AMAP, M_ZERO);
Fixed

2021-04-06 10:52 UTC, pj1031999 commented
> What do you think about moving tests into `sys/tests/uvm.c`. Then we will have all tests in one place.

I'm not sure. From my point of view amap is a separate structure that can live without rest of UVM. But if you thing that one place for all tests is a better idea you can push that directly here. It's not a a big thing for me.

2021-04-06 11:13 UTC, pj1031999 commented
> I would be happy to see assertions about held lock in functions that require it (at least in functions `*_nolock`). It could help in future.

Hm... I'm not sure if it's necessary. That functions are private for amap and called only from their locked brothers now.
I've checked that and we have 5 `_nolock` functions in our code and only one has that assertion.
I can add them but I don't see a reason for that now.

2021-04-09 06:24 UTC, franciscozdo approved these changes

2021-04-26 11:10 UTC, franciscozdo requested changes

2021-04-26 11:10 UTC, franciscozdo commented on include/sys/vm_amap.h
> +  int *am_bckptr; /* (@) stack of used anons - refers to am_anon & am_slots */
According to UVM functionality of am_slot and am_backptr should be swapped.

2023-02-24 16:41 UTC, franciscozdo commented
@cahirwpz I think that it can be closed hence I will implement UVM like subsystem in #1379 and later PRs.

2023-05-19 11:10 UTC, cahirwpz commented
Closing the PR as requested in https://github.com/cahirwpz/mimiker/pull/1072#issuecomment-1443985549

2023-05-19 11:10 UTC, closed without merging