Onboarding note
cahirwpz/mimiker pull request #1098
Opened 2021-04-26 11:27 UTC by hadarai

It's onboarding for any new in the project.
It's supposed to contain:
- project general overview
- description of file hirarchy 
- description of CI
- Licence description
- General tips for work in project

2021-05-18 10:02 UTC, cahirwpz commented
@hadarai Have you looked into how the file is actually rendered by GitHub interface? I think that `^1` stuff doesn't work as intended. Please have a look at [markdown cheatsheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf). The construct you used is not listed there.

2021-05-18 10:10 UTC, hadarai commented
> @hadarai Have you looked into how the file is actually rendered by GitHub interface? I think that `^1` stuff doesn't work as intended. Please have a look at [markdown cheatsheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf). The construct you used is not listed there.

Done.

2021-05-31 10:50 UTC, pwit81 commented on wiki/docs/onboarding.md
> +  is that all header files are the same as NetBSD's.
Which header files are the same? Please specify.

2021-05-31 11:09 UTC, pwit81 requested changes
Please apply more Markdown formatting. E.g. individual names like FreeBSD should be formatted `FreeBSD`. See also detailed comment in the note text.

2021-05-31 11:09 UTC, pwit81 commented on wiki/docs/onboarding.md
> +* QEMU - virtual machine allowing us to run system
> QEMU - system emulator allowing us to run MIPS and AArch64 guest code on x86-64 hosts.

2021-06-06 10:42 UTC, wiklam commented on wiki/docs/onboarding.md
> +system for Malta board and Raspberry Pi 3.
```suggestion
Mimiker is an experimental implementation of a simple UNIX-like operating
system for the Malta board and Raspberry Pi 3.
```

2021-06-06 10:42 UTC, wiklam commented on wiki/docs/onboarding.md
> +The other one there can be Korn Shell working in the system.
```suggestion
When you turn on the system with `./launch` [script][1] system is being run in QEMU.
Multiple terminals are connected to VM. Between these you can switch with Tmux.
One of them is klog (log with kernel messages), the second one is GDB.
The other one there can be Korn Shell working in the system.
```

2021-06-06 10:42 UTC, wiklam commented on wiki/docs/onboarding.md
> +  everything here is compatible with NetBSD and standard C library.
```suggestion
  everything here is compatible with NetBSD and the standard C library.
```

2021-06-11 12:36 UTC, pwit81 approved these changes

2021-06-11 20:20 UTC, wiklam approved these changes
OK

2021-06-11 20:20 UTC, wiklam commented on wiki/docs/onboarding.md
> +* We love to KISS
```suggestion
* we want kernel to be run on a modern architecture, we started with MIPS32,
  but currently we are switching to AArch64 (Raspberry Pi 3)
* we love to KISS
```
The previous sentences are lower case

2021-06-12 10:01 UTC, cahirwpz approved these changes

2021-06-12 10:02 UTC, merged