Check pointer size instead of architecture in memory related tests
cahirwpz/mimiker pull request #1192
Opened 2022-01-08 11:22 UTC by MichalBlk

2022-01-08 18:40 UTC, pj1031999 approved these changes

2022-01-09 10:58 UTC, wiklam approved these changes

2022-01-14 13:20 UTC, cahirwpz requested changes
I'm in favour of this change. However we should sort out other places that refer to macros that encode bitness of an architecture, i.e. `_LP64`.

2022-01-14 13:44 UTC, cahirwpz approved these changes

2022-01-14 13:44 UTC, merged