AArch64: save FPU context on ctx_switch, restore on user_exc_leave.
cahirwpz/mimiker pull request #931
Opened 2021-01-16 22:40 UTC by pj1031999

Port #928 for _AArch64_.

2021-01-18 21:41 UTC, cahirwpz commented
Could you move MIPS implementation to separate PR?

2021-01-18 21:49 UTC, pj1031999 commented
@cahirwpz see #928.

2021-01-29 13:07 UTC, franciscozdo requested changes
I suggest rewriting comments then code will be more reader friendly. Also I don't understand one use of `TDP_FPUCTXSAVED` flag.

2021-01-29 13:07 UTC, franciscozdo commented on sys/aarch64/evec.S
> +        load_fpu_ctx x1, x2, w2 /* 2nd and 3rd argument must be the same */
Here I would write sth like '2nd and 3rd argument must be register and its lower half'.

2021-01-29 13:07 UTC, franciscozdo commented on sys/aarch64/switch.S
> +        save_fpu_ctx x2, x3, w3
Here you should also add a comment about 2nd and 3rd argument as you did before.

2021-01-29 13:27 UTC, pj1031999 commented on sys/aarch64/evec.S
> + * xtmp & wtmp MUST BE the same register - fpcr and fpsr are 32-bit registers
done

2021-01-29 13:27 UTC, pj1031999 commented on sys/aarch64/switch.S
> + * xtmp & wtmp MUST BE the same register - fpcr and fpsr are 32-bit registers
done

2021-01-29 13:27 UTC, pj1031999 commented on sys/aarch64/switch.S
> +        and     w2, w3, #TDP_FPUINUSE|TDP_FPUCTXSAVED
I use that flag.

2021-01-29 13:40 UTC, cahirwpz approved these changes
LGTM

2021-01-29 13:42 UTC, merged